# http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/sample-templates-services-us-west-2.html#w1ab2c21c45c15c15
# Amazon EC2 instance in a security group Creates an Amazon EC2 instance in an Amazon EC2 security group.
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template EC2InstanceWithSecurityGroupSample:
  Create an Amazon EC2 instance running the Amazon Linux AMI. The AMI is chosen based
  on the region in which the stack is run. This example creates an EC2 security group
  for the instance to give you SSH access. **WARNING** This template creates an Amazon
  EC2 instance. You will be billed for the AWS resources used if you create a stack
  from this template.'
Parameters:
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  NodeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp:
          Ref: SSHLocation
  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Kubernetes ports for control plane per https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html
  WorkerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Kubernetes ports for workers per https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html
  ControlPlaneSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Fn::GetAtt: [ ControlPlaneSecurityGroup, GroupId ]
      IpProtocol: tcp
      FromPort: '443'
      ToPort: '443'
      SourceSecurityGroupId: 
        Fn::GetAtt: [ WorkerSecurityGroup, GroupId ]
    DependsOn: ControlPlaneSecurityGroup
  ControlPlaneSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId:
        Fn::GetAtt: [ ControlPlaneSecurityGroup, GroupId ]
      IpProtocol: tcp
      FromPort: '1025'
      ToPort: '65535'
      SourceSecurityGroupId: 
        Fn::GetAtt: [ WorkerSecurityGroup, GroupId ]
    DependsOn: ControlPlaneSecurityGroup
  WorkerSecurityGroupCPHTTPSIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Fn::GetAtt: [ WorkerSecurityGroup, GroupId ]
      IpProtocol: tcp
      FromPort: '443'
      ToPort: '443'
      SourceSecurityGroupId:
        Fn::GetAtt: [ ControlPlaneSecurityGroup, GroupId ]
    DependsOn: WorkerSecurityGroup
  WorkerSecurityGroupCPIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Fn::GetAtt: [ WorkerSecurityGroup, GroupId ]
      IpProtocol: tcp
      FromPort: '1025'
      ToPort: '65535'
      SourceSecurityGroupId: 
        Fn::GetAtt: [ ControlPlaneSecurityGroup, GroupId ]
    DependsOn: WorkerSecurityGroup
  WorkerSecurityGroupWorkeIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId:
        Fn::GetAtt: [ WorkerSecurityGroup, GroupId ]
      IpProtocol: '-1'
      SourceSecurityGroupId: 
        Fn::GetAtt: [ WorkerSecurityGroup, GroupId ]
    DependsOn: WorkerSecurityGroup
  WorkerSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId:
        Fn::GetAtt: [ WorkerSecurityGroup, GroupId ]
      IpProtocol: '-1'
      CidrIp: '0.0.0.0/0'
    DependsOn: WorkerSecurityGroup
Outputs:
  NodeSecGroup:
    Description: Security Group for all nodes
    Value:
      Ref: NodeSecurityGroup
    Export: 
      Name: NodeSecGroup
  ControlPlaneSecGroup:
    Description: Security Group for all control planes
    Value:
      Ref: ControlPlaneSecurityGroup
    Export: 
      Name: ControlPlaneSecGroup
  WorkerSecGroup:
    Description: Security Group for all workers
    Value:
      Ref: WorkerSecurityGroup
    Export: 
      Name: WorkerSecGroup
